-- Populate precomputed tables with current hot and most-played game lists
-- Run this after creating the tables, and refresh periodically (daily/weekly)

-- Clear existing data
TRUNCATE TABLE public.hot_game_names;
TRUNCATE TABLE public.most_played_game_names;

-- Populate hot games (50 games)
INSERT INTO public.hot_game_names (best_name_norm, rank) VALUES
  ('covenant', 1),
  ('recall', 2),
  ('deckers', 3),
  ('tax the rich', 4),
  ('children of the colossi', 5),
  ('kuldhara', 6),
  ('orloj: the prague astronomical clock', 7),
  ('the hobbit: there and back again', 8),
  ('seti: space agencies', 9),
  ('feya''s swamp', 10),
  ('the lord of the rings: duel for middle-earth – allies', 11),
  ('seti: search for extraterrestrial intelligence', 12),
  ('speakeasy', 13),
  ('the old king''s crown', 14),
  ('the lord of the rings: fate of the fellowship', 15),
  ('sanctuary', 16),
  ('bohemians', 17),
  ('tag team', 18),
  ('vantage', 19),
  ('gelati', 20),
  ('the druids of edora', 21),
  ('take time', 22),
  ('ayar: children of the sun', 23),
  ('ark nova', 24),
  ('galileo''s truth', 25),
  ('the lord of the rings: duel for middle-earth', 26),
  ('1ers contacts', 27),
  ('wispwood', 28),
  ('emberheart', 29),
  ('lost ruins of arnak: twisted paths', 30),
  ('ants', 31),
  ('lost ruins of arnak', 32),
  ('brass: birmingham', 33),
  ('coming of age', 34),
  ('galactic cruise', 35),
  ('forestry', 36),
  ('federation: piracy', 37),
  ('nature', 38),
  ('echoes of time', 39),
  ('arcs', 40),
  ('the elder scrolls: betrayal of the second era', 41),
  ('bomb busters', 42),
  ('terraforming mars', 43),
  ('kingdom crossing', 44),
  ('castle combo', 45),
  ('luthier', 46),
  ('slay the spire: the board game', 47),
  ('origin story', 48),
  ('harmonies', 49),
  ('tainted grail: the fall of avalon', 50);

-- Populate most played games (25 games)
INSERT INTO public.most_played_game_names (best_name_norm, rank) VALUES
  ('flip 7', 1),
  ('ark nova', 2),
  ('harmonies', 3),
  ('castle combo', 4),
  ('bomb busters', 5),
  ('forest shuffle', 6),
  ('sea salt & paper', 7),
  ('terraforming mars', 8),
  ('azul', 9),
  ('wingspan', 10),
  ('the lord of the rings: fate of the fellowship', 11),
  ('faraway', 12),
  ('sky team', 13),
  ('cascadia', 14),
  ('lost ruins of arnak', 15),
  ('heat: pedal to the metal', 16),
  ('vantage', 17),
  ('seti: search for extraterrestrial intelligence', 18),
  ('the white castle', 19),
  ('scout', 20),
  ('7 wonders duel', 21),
  ('carcassonne', 22),
  ('the gang', 23),
  ('the lord of the rings: the fellowship of the ring – trick-taking game', 24),
  ('splendor', 25);

